### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by irvintim** [ben8p/gnome-extension-workspace-titles#1]
Hey Ben,

Thanks for making this available, I think it's what I am looking for, but I can't figure out how to use this extension.  I'm trying to be able to dynamically name the workspaces as I create them and put like items together.

**Comment by ben8p** [comment]
Hi
When you open the overview panel (for instance by pressing the "windows" key on the keyboard) you see the opened windows and on the right the list of workspaces.

At the bottom of each workspace thumbnail you should see a black rectangle with "untitled" in it.

If you click on the word "untitled" you can type a new content. There's no visible cursor so one may think it does not allow to type.
But if you start typing it should update the content.

**Comment by irvintim** [comment]
Thanks for getting back to me.  Unfortunately, that doesn't work.  I'm guessing I have some other extension getting in the way.  When I hit the Super/Windows key if I have "Workspaces to Dock" the name at the bottom of the thumbnails for each workspace says "Workspace 1", "Workspace 2", etc. If I click on that and try to type nothing happens.  If I have "Workspaces to Dock" turned off then the thumbnails don't have a caption at all, so I can't see the titles.

I am on Ubuntu 20.04, Gnome shell v 3.36.

Not a big deal if you don't have another suggestion, I'll work on plan B.

**Comment by ben8p** [comment]
I use gnome 3.28.2 (and cannot upgrade unfortunately).

Maybe there's a difference there.
I don't expect it to work with the "workspace to dock" extension.

When pressing the Super key you should see:

![Screenshot-20210728093339-2557x1439](https://user-images.githubusercontent.com/3725579/127283008-e68109a2-c82a-4aea-a631-8b8cedc3494a.png)

I assume you see the thumbnails but not the black rectangle ?

If you have time and are willing to use some for debugging maybe you cal help me find what's wrong ?

If you press `Super`, then (while in the overview panel) you press `Alt + F2` then type `lg` you will open a debugger window.
In the debugger window, type `imports.ui.main.overview._controls._thumbnailsBox._thumbnails` then `ENTER`.
Can you share the output ?

In my case, I see:
![Screenshot-20210728094004-831x50](https://user-images.githubusercontent.com/3725579/127283505-8c84273c-dcfc-4531-8bdc-bd425ddcb95f.png)

**Comment by irvintim** [comment]
I turned off `Workspace to Dock`.  Pressing the `Super` key I see this, the thumbnails without the black rectangle:
![workspace-titles](https://user-images.githubusercontent.com/5721686/127367571-4ff95023-2816-4210-ad73-39c01a211a41.png)

Running the `lg` debug command you asked for I get:
![lg-output](https://user-images.githubusercontent.com/5721686/127367650-f8b29cf4-cea7-40c6-960b-8534027c68b4.png)

Let me know if there is anything else you want me to try.

**Comment by irvintim** [comment]
BTW, when I turn `Workspace to Dock` back on I do get the black rectangles with the title shown in the thumbnails in the dock.  Just FYI.
![ws-to-dock](https://user-images.githubusercontent.com/5721686/127368755-458b5dd8-3915-4900-924c-2b30f8a9292c.png)

**Comment by ben8p** [comment]
Thanks for sharing this.
The name you see with workspace to dock extension are from the extension and not added by my extension.

The debug info you gave is interesting. It seems gnome deva changed where the thumbnail object are stored.

Because gnome documentation is somewhat poor, the only way to find new location is to fiddle around...

You would need to put `imports.ui.main.overview` in the debug window then explore the output object searching for an object with the property `_thumbnails`.
It's a little cumbersome to do and I would understand if you give up.
I unfortunately don't have access to the same version of gnome you have so I can't do it myself.

**Comment by irvintim** [comment]
Found it (there was an extra `_overview`):
![image](https://user-images.githubusercontent.com/5721686/127383238-329e20e3-e5c9-436a-a834-e91cfdeffb0f.png)

Here's the output:
![image](https://user-images.githubusercontent.com/5721686/127383402-43853b17-d059-4f68-8d2f-1d85fd0868a5.png)

**Comment by ben8p** [comment]
Awesome!
Thanks a lot for this!

I should be able to update the code quickly and hopefully tomorrow at the same time you will receive the update!

Once it's published, I'll add a comment here.

**Comment by ben8p** [comment]
Hi, 
the update is published

Let me know if that fix the issue

**Comment by ben8p** [comment]
Hi,
I published a version 4 as it seems the version 3 had issues.


Let me know if it works for you

**Comment by irvintim** [comment]
That works!  Thanks for the extension, and for the fix.
