### ISSUE TITLE
Wont install on  Gnome 3.36.8

### ISSUE THREAD

**Issue by Fury1** [ben8p/gnome-extension-workspace-titles#2]
This extension is exactly what I was looking for, however, it errors out when installing from the Gnome extensions website.  I noticed the downloads for Gnome 3.36 only go to extension point release 3.  Any chance there is a simple fix for .3 on support?

Edit:
Checked  logs for extension error:  

/extension.js 25]: reference to undefined property "_controls"

**Comment by ben8p** [comment]
Hi,
Do you have the version 3 if the extension? (Released about 6 hours ago)

**Comment by Fury1** [comment]
I did, I also submitted a pull request with some changes that get it working for me.

#3

**Comment by ben8p** [comment]
Thanks,
I will take a look at the pull request and prepare a new release.

I'll add a comment here when the new release is published

**Comment by Fury1** [comment]
Sounds good, great extension by the way, long overdue for Gnome.

**Comment by ben8p** [comment]
Hi,
I used the logic of you pull request and added some flexibility for future case.

It is merged and a new version is published.  
Can you try to install the version 4 ?

Thanks for the contribution

**Comment by Fury1** [comment]
Seems to be working out of the box now off of the Gnome extensions website. I think we are good to go.

**Comment by ben8p** [comment]
Awesome, thanks!
